jQuery ->
	$('.display').siblings('.veto').hide()
	$('.display').siblings('.add_vote').hide()
	$('.no_display').hide()
	$('#do_not_play_chart_songs').find('.add_vote').hide()
	$('#do_not_play_chart_songs').find('.remove_vote').hide()
	$('#chart_songs').find('.remove_dnp').hide()
	$('#new_vote').hide()
	$('.add_vote').on 'click', (event) ->
		event.preventDefault()
		$(event.target).siblings('.remove_vote').show().addClass('disabled')
		$(event.target).siblings('.veto').hide()
		$(event.target).hide()
	$('.remove_vote').on 'click', (event) ->
		event.preventDefault()
		if (!($(event.target).hasClass('disabled')))
			$(event.target).siblings('.add_vote').show().addClass('disabled')
			$(event.target).siblings('.veto').show().addClass('disabled')
			$(event.target).hide()
	$('.veto').on 'click', (event) ->
		event.preventDefault()
		$(event.target).siblings('.remove_dnp').show().addClass('disabled')
		$(event.target).hide()
		$(event.target).siblings('.add_vote').hide()
		dnp = $(event.target).parent().parent()
		$('#do_not_play_chart_songs').find('#dnp_' + dnp.attr('id')).append(dnp.contents())
		dnp.html('')
	$('.remove_dnp').on 'click', (event) ->
		event.preventDefault()
		$(event.target).siblings('.add_vote').show()
		$(event.target).siblings('.veto').show()
		$(event.target).hide()
		play = $(event.target).parent().parent()
		$('#chart_songs').find('#' + play.attr('id').match(/\d+/)).append(play.contents())
		play.html('')